'use client'
import axios from 'axios';
import React, { useEffect, useState, useContext } from 'react';
import { useRouter } from 'next/navigation';
import { 
    RiUserLine, 
    RiMailLine, 
    RiPhoneLine, 
    RiMapPinLine, 
    RiFlagLine, 
    RiSave3Line, 
    RiLockPasswordLine,
    RiCommunityLine,
    RiNavigationLine,
    RiInboxLine
} from 'react-icons/ri';
import { Context } from '@/component/helper/Context';
import toast from 'react-hot-toast';

const SettingsPage = () => {
    const router = useRouter();
    const { userData } = useContext(Context);
    
    const [saving, setSaving] = useState(false);
    
    const [formData, setFormData] = useState({
        name: '',
        phone: '',
        city: '',
        country: '',
        address_line1: '',
        address_line2: '',
        state: '',
        postal_code: '',
        password: '',
    });

    useEffect(() => {
        if (userData) {
            setFormData({
                name: userData.name || '',
                phone: userData.phone || '',
                city: userData.city || '',
                country: userData.country || '',
                address_line1: userData.address_line1 || '',
                address_line2: userData.address_line2 || '',
                state: userData.state || '',
                postal_code: userData.postal_code || '',
                password: '', 
            });
        }
    }, [userData]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setSaving(true);
        try {
            const dataToSubmit = { 
                id: userData.user_id,
                ...formData 
            };
            if (!dataToSubmit.password) {
                delete dataToSubmit.password; 
            }
            
            const res = await axios.patch('/api/user', dataToSubmit, { withCredentials: true });
            
            if (res.data.success) {
                toast.success('Settings updated successfully!');
                window.location.reload(); 
            } else {
                toast.error(res.data.message || 'Failed to update settings');
            }
        } catch (error) {
            console.error('Update Error:', error);
            toast.error(error?.response?.data?.message || 'Update failed');
        } finally {
            setSaving(false);
        }
    };

    if (!userData) return (
        <div className="flex items-center justify-center min-h-[400px]">
            <div className="w-10 h-10 border-4 border-slate-100 border-t-emerald-500 rounded-full animate-spin"></div>
        </div>
    );

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            <div className="border-b border-slate-200 pb-4">
                <h1 className="text-xl font-bold text-slate-900 uppercase tracking-tight">Account Settings</h1>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest mt-1">Manage your personal information and security.</p>
            </div>

            <div className="bg-white border border-slate-200">
                <form onSubmit={handleSubmit} className="flex flex-col">

                    {/* Avatar */}
                    <div className="flex items-center gap-5 p-6 border-b border-slate-100">
                        <div className="w-14 h-14 border border-slate-200 bg-slate-900 text-white flex items-center justify-center text-xl font-bold shrink-0">
                            {userData.name?.charAt(0) || 'U'}
                        </div>
                        <div>
                            <p className="font-bold text-slate-900 text-xs uppercase tracking-tight leading-none mb-1">Profile Avatar</p>
                            <p className="text-[9px] text-slate-400 font-bold uppercase tracking-widest">Autogenerated from your name.</p>
                        </div>
                    </div>

                    <div className="p-6 space-y-8">
                        {/* Basic Identity */}
                        <div className="space-y-4">
                            <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest border-l-2 border-slate-900 pl-3">Basic Identity</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Full Name</label>
                                    <div className="relative">
                                        <RiUserLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="name" value={formData.name} onChange={handleChange} required className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Email (Read Only)</label>
                                    <div className="relative">
                                        <RiMailLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="email" value={userData.email || ''} disabled className="w-full bg-slate-100 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold text-slate-400 cursor-not-allowed" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Phone Number</label>
                                    <div className="relative">
                                        <RiPhoneLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="tel" name="phone" value={formData.phone} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">New Password</label>
                                    <div className="relative">
                                        <RiLockPasswordLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="password" name="password" value={formData.password} onChange={handleChange} placeholder="Leave blank to keep current" className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Address */}
                        <div className="space-y-4">
                            <h4 className="text-[9px] font-bold text-slate-400 uppercase tracking-widest border-l-2 border-slate-900 pl-3">Localization & Address</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="flex flex-col gap-1.5 md:col-span-2">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Address Line 1</label>
                                    <div className="relative">
                                        <RiNavigationLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="address_line1" value={formData.address_line1} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5 md:col-span-2">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Address Line 2</label>
                                    <div className="relative">
                                        <RiCommunityLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="address_line2" value={formData.address_line2} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">City</label>
                                    <div className="relative">
                                        <RiMapPinLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="city" value={formData.city} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">State / Province</label>
                                    <input type="text" name="state" value={formData.state} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Postal / Zip Code</label>
                                    <div className="relative">
                                        <RiInboxLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="postal_code" value={formData.postal_code} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-1.5">
                                    <label className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Country</label>
                                    <div className="relative">
                                        <RiFlagLine className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
                                        <input type="text" name="country" value={formData.country} onChange={handleChange} className="w-full bg-slate-50 border border-slate-200 pl-9 pr-4 py-2.5 text-xs font-bold focus:outline-none focus:border-slate-400 transition-all" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex justify-end">
                        <button
                            type="submit"
                            disabled={saving}
                            className="px-8 py-2.5 bg-slate-900 text-white font-bold text-[10px] uppercase tracking-widest hover:bg-slate-800 transition-all disabled:opacity-50 flex items-center gap-2 min-w-[180px] justify-center"
                        >
                            {saving ? (
                                <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                            ) : (
                                <><RiSave3Line size={16} /> Save Changes</>
                            )}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default SettingsPage;
