'use client'
import axios from 'axios';
import React, { useEffect, useState, useContext } from 'react';
import { useRouter } from 'next/navigation';
import { 
    RiUserLine, 
    RiMailLine, 
    RiPhoneLine, 
    RiMapPinLine, 
    RiFlagLine, 
    RiSave3Line, 
    RiLockPasswordLine,
    RiCommunityLine,
    RiNavigationLine,
    RiInboxLine
} from 'react-icons/ri';
import { Context } from '@/component/helper/Context';
import toast from 'react-hot-toast';

const SettingsPage = () => {
    const router = useRouter();
    const { userData } = useContext(Context);
    
    const [saving, setSaving] = useState(false);
    
    const [formData, setFormData] = useState({
        name: '',
        phone: '',
        city: '',
        country: '',
        address_line1: '',
        address_line2: '',
        state: '',
        postal_code: '',
        password: '',
    });

    useEffect(() => {
        if (userData) {
            setFormData({
                name: userData.name || '',
                phone: userData.phone || '',
                city: userData.city || '',
                country: userData.country || '',
                address_line1: userData.address_line1 || '',
                address_line2: userData.address_line2 || '',
                state: userData.state || '',
                postal_code: userData.postal_code || '',
                password: '', 
            });
        }
    }, [userData]);

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setSaving(true);
        try {
            const dataToSubmit = { 
                id: userData.user_id,
                ...formData 
            };
            if (!dataToSubmit.password) {
                delete dataToSubmit.password; 
            }
            
            const res = await axios.patch('/api/user', dataToSubmit, { withCredentials: true });
            
            if (res.data.success) {
                toast.success('Settings updated successfully!');
                window.location.reload(); 
            } else {
                toast.error(res.data.message || 'Failed to update settings');
            }
        } catch (error) {
            console.error('Update Error:', error);
            toast.error(error?.response?.data?.message || 'Update failed');
        } finally {
            setSaving(false);
        }
    };

    if (!userData) return (
        <div className="flex items-center justify-center min-h-[400px]">
            <div className="w-10 h-10 border-4 border-slate-100 border-t-emerald-500 rounded-full animate-spin"></div>
        </div>
    );

    return (
        <div className="max-w-4xl mx-auto py-8 px-4 space-y-8">
            <div className="flex flex-col gap-1">
                <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Account Settings</h1>
                <p className="text-slate-500 text-sm font-medium">Manage your personal information and security.</p>
            </div>

            <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                <form onSubmit={handleSubmit} className="flex flex-col gap-10">
                    
                    <div className="flex items-center gap-6 pb-8 border-b border-slate-100">
                        <div className="w-20 h-20 rounded-2xl bg-emerald-500 text-white flex items-center justify-center text-3xl font-bold shrink-0">
                            {userData.name?.charAt(0) || 'U'}
                        </div>
                        <div>
                            <h3 className="font-bold text-slate-800 text-lg">Profile Avatar</h3>
                            <p className="text-slate-400 text-xs font-medium">Autogenerated from your legal name.</p>
                        </div>
                    </div>

                    <div className="space-y-8">
                        {/* Section 1: Basic Identity */}
                        <div className="space-y-4">
                            <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest border-l-4 border-emerald-500 pl-3">Basic Identity</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Full Name</label>
                                    <div className="relative">
                                        <RiUserLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="name" value={formData.name} onChange={handleChange} required className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Email (Read Only)</label>
                                    <div className="relative">
                                        <RiMailLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="email" value={userData.email || ''} disabled className="input-standard pl-11 bg-slate-100 text-slate-400 cursor-not-allowed" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Phone Number</label>
                                    <div className="relative">
                                        <RiPhoneLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="tel" name="phone" value={formData.phone} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-emerald-600 uppercase tracking-wider ml-1">New Password</label>
                                    <div className="relative">
                                        <RiLockPasswordLine className="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-500" />
                                        <input type="password" name="password" value={formData.password} onChange={handleChange} placeholder="••••••••" className="input-standard pl-11 !bg-emerald-50/30 !border-emerald-100 focus:!border-emerald-500" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Section 2: Localization & Address */}
                        <div className="space-y-4">
                            <h4 className="text-xs font-black text-slate-400 uppercase tracking-widest border-l-4 border-emerald-500 pl-3">Localization & Address</h4>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="flex flex-col gap-2 md:col-span-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Address Line 1</label>
                                    <div className="relative">
                                        <RiNavigationLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="address_line1" value={formData.address_line1} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2 md:col-span-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Address Line 2</label>
                                    <div className="relative">
                                        <RiCommunityLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="address_line2" value={formData.address_line2} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">City</label>
                                    <div className="relative">
                                        <RiMapPinLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="city" value={formData.city} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">State / Province</label>
                                    <input type="text" name="state" value={formData.state} onChange={handleChange} className="input-standard" />
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Postal / Zip Code</label>
                                    <div className="relative">
                                        <RiInboxLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="postal_code" value={formData.postal_code} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                                <div className="flex flex-col gap-2">
                                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider ml-1">Country</label>
                                    <div className="relative">
                                        <RiFlagLine className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                        <input type="text" name="country" value={formData.country} onChange={handleChange} className="input-standard pl-11" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="pt-6 border-t border-slate-100 flex justify-end">
                        <button 
                            type="submit" disabled={saving}
                            className="px-10 py-4 bg-slate-900 text-white rounded-xl font-bold text-sm flex items-center justify-center gap-2 hover:bg-emerald-500 transition-all disabled:opacity-70 min-w-[200px]"
                        >
                            {saving ? (
                                <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                            ) : (
                                <>
                                    <RiSave3Line size={20} />
                                    Synchronize Profile
                                </>
                            )}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default SettingsPage;
