const packages = [
  {
    id: 1,
    category: "webdesign",
    pack: "Basic",
    title: "Figma Landing Page Design",
    price: 100,
    description:
      "Custom Landing Page Design (Up to 5 Sections) with Figma | Responsive | No Coding | Discuss More",
    features: [
      "1 page",
      "Responsive design",
      "Source file",
      "Unlimited Revisions",
      "3-day delivery",
    ],
  },
  {
    id: 2,
    category: "webdesign",
    pack: "Standard",
    title: "Homepage + 4 Inner Pages in Figma",
    price: 400,
    description:
      "Unique Web Homepage + 4 Inner Pages Design in Figma (Desktop + Mobile) | No Coding | Discuss More",
    features: [
      "5 pages",
      "Responsive design",
      "Source file",
      "Unlimited Revisions",
      "7-day delivery",
    ],
  },
  {
    id: 3,
    category: "webdesign",
    pack: "Premium",
    title: "Homepage + 9 Inner Pages in Figma",
    price: 800,
    description:
      "Unique Web Homepage + 9 Inner Pages Design in Figma (Desktop + Mobile) | No Coding | Discuss More",
    features: [
      "10 pages",
      "Responsive design",
      "Source file",
      "Unlimited Revisions",
      "10-day delivery",
    ],
  },
  {
    id: 4,
    category: "webdevelopment",
    pack: "Basic",
    title: "Single Page Website",
    price: 300,
    description:
      "A modern single-page responsive website for small businesses or personal use.",
    features: [
      "1 page",
      "Responsive layout",
      "SEO optimization",
      "Basic contact form",
      "5-day delivery",
    ],
  },
  {
    id: 5,
    category: "webdevelopment",
    pack: "Standard",
    title: "Business Website (5 Pages)",
    price: 800,
    description:
      "A fully functional responsive website for startups or small businesses.",
    features: [
      "5 pages",
      "Responsive design",
      "SEO-friendly",
      "Contact form + Google Maps",
      "7-day delivery",
    ],
  },
  {
    id: 6,
    category: "webdevelopment",
    pack: "Premium",
    title: "E-commerce Website",
    price: 2000,
    description:
      "Custom e-commerce website with product catalog and shopping cart.",
    features: [
      "10+ pages",
      "E-commerce functionality",
      "Payment gateway integration",
      "Admin dashboard",
      "14-day delivery",
    ],
  },
  {
    id: 7,
    category: "graphicsdesign",
    pack: "Basic",
    title: "Logo Design",
    price: 100,
    description: "Professional custom logo design for your brand.",
    features: [
      "3 initial concepts",
      "High-resolution files",
      "Transparent background",
      "Unlimited revisions",
      "3-day delivery",
    ],
  },
  {
    id: 8,
    category: "graphicsdesign",
    pack: "Standard",
    title: "Brand Identity Pack",
    price: 400,
    description: "Logo + business card + letterhead + social media kit.",
    features: [
      "Logo design",
      "Business card",
      "Letterhead",
      "Social media kit",
      "7-day delivery",
    ],
  },
  {
    id: 9,
    category: "graphicsdesign",
    pack: "Premium",
    title: "Full Brand Design",
    price: 1000,
    description: "Complete branding solution for businesses.",
    features: [
      "Logo + branding guide",
      "Stationery design",
      "Social media branding",
      "Presentation template",
      "14-day delivery",
    ],
  },
  {
    id: 10,
    category: "care",
    pack: "Basic",
    title: "Basic IT Care Plan",
    price: 200,
    description: "Monthly IT support plan for small businesses.",
    features: [
      "Monthly security updates",
      "Basic website monitoring",
      "Email support",
      "Weekly backups",
      "24-hour response time",
    ],
  },
  {
    id: 11,
    category: "care",
    pack: "Standard",
    title: "Standard IT Care Plan",
    price: 500,
    description: "Professional IT maintenance with added support.",
    features: [
      "All Basic plan features",
      "Performance optimization",
      "Priority email + chat support",
      "Daily backups",
      "12-hour response time",
    ],
  },
  {
    id: 12,
    category: "care",
    pack: "Premium",
    title: "Premium IT Care Plan",
    price: 1200,
    description: "Full IT management for growing businesses.",
    features: [
      "All Standard plan features",
      "24/7 monitoring",
      "Dedicated IT manager",
      "Disaster recovery plan",
      "1-hour response time",
    ],
  },
];

export default packages;
